version: "3.9"
services: 
  great_expectations: 
    image: "greatexpectations/great_expectations:python-3.7-buster-ge-0.12.0"
    volumes: 
      - .:/app
  test: 
    build: . 
    image: "great-expectations"
    volumes: 
      - .:/app
    command: python3 -m pytest